In [71]:
import numpy as np
A = np.array([[1,2,1],[2,2,3]])
B = np.array([3,4,5])

In [72]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [73]:
np.subtract(A,B)

array([[-2, -2, -4],
       [-1, -2, -2]])

In [74]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [75]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [76]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]], dtype=int32)

In [77]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]], dtype=int32)