In [1]:
# Libraries

In order to get libraries and its functionalities we have 3 approaches <br>
1. get  a specific function from the library<br> Syntax - from \<library name> import \<function name><br>
2. get the entire library<br>Syntax -  import \<library name><br>
3. get the entire library with a alias name<br>Syntax -  import \<libarary name> as \<any alias name><br>


In [2]:
sqrt(16)

NameError: name 'sqrt' is not defined

In [3]:
from math import sqrt

In [4]:
sqrt(16)

4.0

In [5]:
pi

NameError: name 'pi' is not defined

In [6]:
math

NameError: name 'math' is not defined

In [7]:
from math import sin, pi

In [8]:
sin(30)

-0.9880316240928618

In [9]:
pi

3.141592653589793

In [10]:
math

NameError: name 'math' is not defined

In [11]:
import math

In [12]:
math.tau

6.283185307179586

In [13]:
math.cos(30)

0.15425144988758405

In [14]:
import math as m

In [15]:
m.e

2.718281828459045

In [16]:
m.cosh(10)

11013.232920103324

In [17]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.10/library/math.html
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measur

In [18]:
# Numpy 
# Pandas
# Matplotlib
# Seaborn
# Plotly
# Scipy
# Scikit-learn
# statsmodels

# Numpy

NUMerical PYthon -  All mathematical and statistical operations are performed using numpy. Python data structures are  - tuple, list, dictionary, set, frozenset, string <br>
Numpy allows the usage of arrays which enbales faster processing of the data.

In [19]:
l1 = [1,2,3,4] # A list may be a contiguos or non contiguous data structure

In [20]:
print(type(l1))

<class 'list'>


In [21]:
# install numpy
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [22]:
import numpy as np

In [23]:
import time # time function in time library captures the time elapsed since epoch time, unix time 
            # epoch time start from January 1st 1970, 00:00:00

In [24]:
time.time()

1701995457.1084661

In [25]:
time.time()

1701995457.181261

In [26]:
1701824582.9134226 - 1701824482.9386158

99.9748067855835

In [27]:
# Average Calculation

In [28]:
X =  np.random.random(100000000)

In [29]:
X

array([0.46378772, 0.50124925, 0.90377749, ..., 0.08196042, 0.66663948,
       0.84516669])

In [30]:
start = time.time()
sum(X)/100000000
stop = time.time()
print(stop -start)

5.634764671325684


In [31]:
start = time.time()
np.mean(X)
stop = time.time()
print(stop -start)

0.049849510192871094


In [32]:
x =  3.19 + 3.19 + 3.19 + 3.19 + 3.19 + 3.19 + 3.19 + 3.19 + 3.19
y = 3.19 * 9

In [33]:
3.1900000000000011 + 3.1900000000000011

6.380000000000003

In [34]:
print(x)
print(y)
print(x==y)

28.710000000000004
28.71
False


In [35]:
a =  3.19 + 3.19 + 3.19 + 3.19 
b = 3.19 * 4
a==b

True

In [36]:
print(a)
print(b)

12.76
12.76


In [37]:
# Arrays in Numpy 

Arrays is a data structure available through numpy that allocates the contiguos memory to the data. arrays are faster list. an array in numpy is called as ndarray. An array is numpy is set of values stored within square brackets seperated by space

In [38]:
# Creaing Arrays
# An array in numpy can be created in two ways:
    # using python lists  - by applying np.array function
    # using builtin functions

In [39]:
# Create a Zero dimensional Array
arr1 = np.array(60)
print(arr1)
print(type(arr1))
print(arr1.ndim)  # count of the number of square brackets at begining /end of the array
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

60
<class 'numpy.ndarray'>
0
()
1
int64


In [40]:
# Create a One dimensional Array
l1 = [1,2,3,4,5,6,7]
arr1 = np.array(l1)
print(l1)
print(arr1)
print(type(arr1))
print(arr1.ndim)  # count of the number of square brackets at begining /end of the array
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

[1, 2, 3, 4, 5, 6, 7]
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
1
(7,)
7
int64


In [41]:
l1 = [1,2,3,4.0,5,6,7]
arr1 = np.array(l1)
print(l1)
print(arr1)
print(type(arr1))
print(arr1.ndim)  # count of the number of square brackets at begining /end of the array
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

[1, 2, 3, 4.0, 5, 6, 7]
[1. 2. 3. 4. 5. 6. 7.]
<class 'numpy.ndarray'>
1
(7,)
7
float64


In [42]:
# Each element inside an array would be of same data type

In [43]:
l1 = [1,2,3,4.0,5,6,'7']
arr1 = np.array(l1)
print(l1)
print(arr1)
print(type(arr1))
print(arr1.ndim)  # count of the number of square brackets at begining /end of the array
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

[1, 2, 3, 4.0, 5, 6, '7']
['1' '2' '3' '4.0' '5' '6' '7']
<class 'numpy.ndarray'>
1
(7,)
7
<U32


In [44]:
l1 = ['Simpli','learn']
arr1 = np.array(l1)
print(l1)
print(arr1)
print(type(arr1))
print(arr1.ndim)  # count of the number of square brackets at begining /end of the array
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

['Simpli', 'learn']
['Simpli' 'learn']
<class 'numpy.ndarray'>
1
(2,)
2
<U6


In [45]:
# Precendence in deciding the data type is string, float, int

In [46]:
# Create a Two dimensional Array
l1 = [[1,2,3,1],[4,5,6,2],[7,8,9,3]]
arr1 = np.array(l1)
print(l1)
print(arr1)
print(type(arr1))
print(arr1.ndim)  # count of the number of square brackets at begining /end of the array
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

[[1, 2, 3, 1], [4, 5, 6, 2], [7, 8, 9, 3]]
[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]]
<class 'numpy.ndarray'>
2
(3, 4)
12
int64


In [47]:
# Create a Three dimensional Array
l1 = [[[1,2,3],[4,5,6],[7,8,9]], [[3,2,3],[6,5,6],[9,8,9]]]
arr1 = np.array(l1)
print(l1)
print(arr1)
print(type(arr1))
print(arr1.ndim)  # count of the number of square brackets at begining /end of the array
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[3, 2, 3], [6, 5, 6], [9, 8, 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 2 3]
  [6 5 6]
  [9 8 9]]]
<class 'numpy.ndarray'>
3
(2, 3, 3)
18
int64


In [48]:
# what if the list of list has varying size
l2 = [[1,2,3], [1,2]]
arr2 =  np.array(l2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

[list([1, 2, 3]) list([1, 2])]
1
(2,)
2
object


/tmp/ipykernel_72/1251578104.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 =  np.array(l2)


In [49]:
# Indexing and Slicing in arrays

In [50]:
X = np.array([0,1,2,3,4,5,6,7,8,9])

In [51]:
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
Y =  np.array([['00', '01','02'], ['10', '11','12'],['20', '21','22']])
print(Y)
              

[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']]


In [53]:
# Index Operator [<index number>]/ Slice Operator [range of indices] 

In [54]:
X[5]

5

In [55]:
X[5] = 222

In [56]:
print(X)

[  0   1   2   3   4 222   6   7   8   9]


In [57]:
X[:4]

array([0, 1, 2, 3])

In [58]:
X[-5]

222

In [59]:
X[-5:-1]

array([222,   6,   7,   8])

In [60]:
X[-1:-5:-1]

array([9, 8, 7, 6])

In [61]:
# Reverse entir array
X[::-1]

array([  9,   8,   7,   6, 222,   4,   3,   2,   1,   0])

In [62]:
X[-1:0:1]

array([], dtype=int64)

In [63]:
print(Y)

[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']]


In [64]:
Y[2,1]

'21'

In [65]:
Y[-1,-2]

'21'

In [66]:
Y[1:,1:]

array([['11', '12'],
       ['21', '22']], dtype='<U2')

In [67]:
Y[0:2,1:]  

array([['01', '02'],
       ['11', '12']], dtype='<U2')

In [68]:
print(Y)

[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']]


In [69]:
l1 = [[[1,2,3],[4,5,6],[7,8,9]], [[3,2,3],[6,5,6],[9,8,9]]]
X = np.array(l1)

In [70]:
print(X)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 2 3]
  [6 5 6]
  [9 8 9]]]


In [71]:
X.shape

(2, 3, 3)

In [72]:
X[1,2,0]

9

In [73]:
X

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 2, 3],
        [6, 5, 6],
        [9, 8, 9]]])

In [74]:
X[:,1,1:]

array([[5, 6],
       [5, 6]])

In [75]:
# Speacialized Array

In [76]:
# Create an 3 x 4 ndarray full of Zeros

X =  np.zeros((3,4))
print(X)
print(X.ndim)
print(X.shape)
print(X.size)
print(X.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
(3, 4)
12
float64


In [77]:
X =  np.zeros((3,4), dtype = 'int')
print(X)
print(X.ndim)
print(X.shape)
print(X.size)
print(X.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
2
(3, 4)
12
int64


In [78]:
# Create an 3 x 2 ndarray full of ones
X =  np.ones((3,2))
print(X)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [79]:
# Create an 4 x 4 ndarray full of seven's
X =  np.full((4,4), 7)
print(X)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [80]:
# Create an 4 x 4 ndarray with diagonals as 3,4,5,6
X = np.diag([3,4,5,6])
print(X)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]]


In [81]:
np.fliplr(X)

array([[0, 0, 0, 3],
       [0, 0, 4, 0],
       [0, 5, 0, 0],
       [6, 0, 0, 0]])

In [82]:
np.flipud(X)

array([[0, 0, 0, 6],
       [0, 0, 5, 0],
       [0, 4, 0, 0],
       [3, 0, 0, 0]])

In [83]:
# Transpose of the Matrix - Row changes to columns and columns to rows

In [84]:
X.T

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [85]:
X = np.ones((4,4))
np.fill_diagonal(X, [3,4,5,6])
print(X)

[[3. 1. 1. 1.]
 [1. 4. 1. 1.]
 [1. 1. 5. 1.]
 [1. 1. 1. 6.]]


In [86]:
# Identity Matrix -  square ndarray with the principal diagonal as 1 and rest as 0

In [87]:
X =  np.eye(4) # Allows to create square and non square matrices with principal diagonal as 1
print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [88]:
X =  np.identity(4)
print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [89]:
Y = np.eye(2,3)
print(Y)

[[1. 0. 0.]
 [0. 1. 0.]]


In [90]:
# arange -  generate a one dimensional numpy array 
# Syntax - np.arange(Start =0, Stop, Step =1)
# 1. np.arange(10)  => np.arange(0, 10, 1)
# 2. np.arange(4,10)=> np.arange(4, 10, 1)
# 3. np.arange(1,25,3) => np.arange(1,25,3)

In [91]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [93]:
np.arange(1,25,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [94]:
np.arange(25,-10,-3)

array([25, 22, 19, 16, 13, 10,  7,  4,  1, -2, -5, -8])

In [95]:
# Linspace -  Linear Spacing - 2 consecutive values will be equally spaced
# Syntax -np.linspace(start, stop(inclusive), no.of elements, endpoint= True)

np.linspace(1,25,10)

array([ 1.        ,  3.66666667,  6.33333333,  9.        , 11.66666667,
       14.33333333, 17.        , 19.66666667, 22.33333333, 25.        ])

In [96]:
P = np.linspace(1,25,10, endpoint = False)

In [97]:
P

array([ 1. ,  3.4,  5.8,  8.2, 10.6, 13. , 15.4, 17.8, 20.2, 22.6])

In [98]:
P[-1]

22.599999999999998

In [99]:
# Reshape - allows to reshape the array to any dimension, maintaining the size of the array

In [100]:
X =  np.arange(1,25)

In [101]:
print(X)
print(X.shape)
print(X.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)
24


In [102]:
X.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [103]:
X.reshape(2,3,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])

In [104]:
X.reshape(3,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [105]:
print(X)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [106]:
X =  np.arange(1,25).reshape(4,6)

In [107]:
print(X)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [108]:
X.reshape(24,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [109]:
X.reshape(1,24)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [110]:
# Ravel  - used to flatten an array -  converting to a 1d array

In [111]:
Y  = np.arange(2,32,2).reshape(3,5)

In [112]:
Y

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [113]:
np.ravel(Y, order = 'C') # C like structure

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [114]:
np.ravel(Y, order = 'F')  # Column Major -  Fortran Like structure

array([ 2, 12, 22,  4, 14, 24,  6, 16, 26,  8, 18, 28, 10, 20, 30])

In [115]:
np.ravel(Y, order = 'A') # fortran index order

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [116]:
np.ravel(Y, order = 'K') # the way stored in Memory

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [117]:
# random SubModule -  A Part of numpy dedicated to generate/Handling random numbers

In [118]:
# rand -  generates random float between open half interval [0,1)
# random - generates random float between open half interval [0,1)
# randint - generates random integers between given interval

In [119]:
X =  np.random.rand(5)
print(X)

[0.96776833 0.6238229  0.98943854 0.46618898 0.29228017]


In [120]:
X =  np.random.rand(4,4)
print(X)

[[0.22325133 0.51572154 0.65614017 0.33617769]
 [0.339532   0.05997647 0.00322112 0.69250813]
 [0.81684317 0.58272361 0.07267401 0.54720266]
 [0.53441843 0.6189414  0.43309607 0.21314778]]


In [121]:
X =  np.random.random(100)
print(X)

[0.31746066 0.00271008 0.26767034 0.7755071  0.07094079 0.47164321
 0.51238258 0.06953653 0.39946916 0.92899777 0.67367993 0.57808986
 0.94103362 0.68226294 0.68559772 0.30170991 0.58037654 0.7501785
 0.92598911 0.70198879 0.61013489 0.3508886  0.83942344 0.97665061
 0.20845733 0.04551963 0.48592886 0.60898237 0.19849667 0.39422291
 0.88929131 0.60578104 0.85782961 0.56794879 0.53341267 0.97215269
 0.65164907 0.98550584 0.77738638 0.37387183 0.62424395 0.44958676
 0.80086966 0.60814321 0.45472784 0.85180046 0.35509744 0.69445862
 0.94236893 0.35457197 0.59372457 0.34689304 0.37792583 0.66401583
 0.48363882 0.02806619 0.04591828 0.83090389 0.24825749 0.3576897
 0.3689602  0.85562489 0.05640501 0.11685931 0.46337658 0.04960105
 0.41058401 0.41101593 0.64186643 0.78459989 0.61181637 0.27240169
 0.89668612 0.11111507 0.47218615 0.93998349 0.3717286  0.91926975
 0.04464891 0.03272874 0.32760343 0.80909885 0.17630458 0.59782718
 0.32454366 0.55189592 0.28281199 0.63212957 0.43226502 0.583464

In [122]:
P  = np.random.randint(20, 30)
print(P)

27


In [123]:
Q = np.random.randint(15,25, size = (3,3))
print(Q)

[[17 17 20]
 [24 15 19]
 [22 18 16]]


In [128]:
# Broadcasting
x =  np.array([2,3])
y = np.array([[1,2,3], [3,4,5]])
              

In [129]:
x*y

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

In [130]:
5 * y

array([[ 5, 10, 15],
       [15, 20, 25]])

In [127]:
y*x

array([[ 2,  6],
       [ 6, 12]])

In [133]:
a =  np.array([2,3])
b =  np.array([[1,4],[5,9]])

In [134]:
a * b

array([[ 2, 12],
       [10, 27]])

In [135]:
s =  'SimpliLearn'

In [136]:
np.char.upper(s)

array('SIMPLILEARN', dtype='<U11')

In [137]:
np.char.replace(s, 'i','q')

array('SqmplqLearn', dtype='<U11')

In [138]:
t =  'Welcomes You'

In [139]:
np.char.add(s,t)

array('SimpliLearnWelcomes You', dtype='<U23')

In [140]:
s.replace('S', 's')

'simpliLearn'