# Numpy - Is a ML library that can handle big matrices and multidimentional data

In [2]:
#import - this key word is used to import python library

import math

a = 16
print(math.sqrt(a))
b = 3.14
print(math.sin(b))

4.0
0.0015926529164868282


# Numpy (Numerical python) is the foundational package for mathematical computing in python 

# Some basic Shape Manipulation functions

In [41]:
import numpy as np # here as is used to give alias name

new_cyclist_trail = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print("Original Array:")
print(new_cyclist_trail)

#ravel function is used to flatten the data
print("\nUse of ravel function")
a = new_cyclist_trail.ravel()
print("\nFlattened Array:")
print(a)

print("\nUse of reshape function")
reshape = new_cyclist_trail.reshape(3,4)
print(reshape)

print("\nUse of resize function")
resize = new_cyclist_trail.resize(2,6)
print(new_cyclist_trail)


print("\nUse of hsplit function")
splitarray = np.hsplit(new_cyclist_trail,3)
print(splitarray)

print("\nUse of hstack function")
array1 = np.array([2,12,44,23,12,7])
array2 = np.array([3,42,5,1,66,99])
stack_array = np.hstack((array1,array2))
print(stack_array)


Original Array:
[[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

Use of ravel function

Flattened Array:
[10 15 17 26 13 19 12 11 21 24 14 23]

Use of reshape function
[[10 15 17 26]
 [13 19 12 11]
 [21 24 14 23]]

Use of resize function
[[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

Use of hsplit function
[array([[10, 15],
       [12, 11]]), array([[17, 26],
       [21, 24]]), array([[13, 19],
       [14, 23]])]

Use of hstack function
[ 2 12 44 23 12  7  3 42  5  1 66 99]

Use of reshape function


### Ravel:
In Python, the ravel() function is a method provided by the NumPy library. It is used to flatten multi-dimensional arrays into a one-dimensional array. The function returns a flattened array, but it does not create a copy of the original array. Instead, it returns a flattened view of the input array.

In [13]:
import numpy as np

# Create a 2D array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Use the ravel() function to flatten the array
flattened_array = original_array.ravel()

print("Original Array:")
print(original_array)

print("\nFlattened Array:")
print(flattened_array)

Original Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]


### Reshape:

The reshape function also changes the shape of an array but does not change the data. It only manipulates the view of the array.
The total number of elements must remain the same after reshaping.
If the size of the new shape is incompatible with the original size, a ValueError will be raised.
It returns a new array with the specified shape, but it may share the same data as the original array.

In [24]:
print("\nUse of reshape function")
reshape = new_cyclist_trail.reshape(3,4)
print(reshape)
reshape1 = new_cyclist_trail.reshape(4,4) # this statement will through an error called value error
print(reshape1)


Use of reshape function
[[10 15 17 26]
 [13 19 12 11]
 [21 24 14 23]]


ValueError: cannot reshape array of size 12 into shape (4,4)

### Resize
The resize function changes the shape and size of an array, potentially adding or removing elements to achieve the desired shape.
If the new size is larger than the original size, the data will be repeated or filled with zeros.
If the new size is smaller, elements will be discarded.
It returns a new array with the specified shape and may create a new copy of the data.

In [26]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Resize to a larger shape
resized_arr = np.resize(arr, (3, 4))
print(resized_arr)

[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]


### hsplit
The hsplit function in NumPy is used to split an array horizontally along its horizontal axis into multiple sub-arrays. Let's see an example of how to use hsplit

In [32]:
import numpy as np

# Create a 2D array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Use hsplit to split the array horizontally
# Here, we are splitting it into two sub-arrays along the second column
sub_arrays = np.hsplit(original_array, 2)

# Display the original and the resulting sub-arrays
print("Original Array:")
print(original_array)

print("\nSplit Arrays:")
for sub_array in sub_arrays:
    print(sub_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Split Arrays:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


### hstack
The hstack function in NumPy is used to stack arrays in sequence horizontally (along the second axis, i.e., columns). Here's an example demonstrating the use of hstack:

In [42]:
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Use hstack to stack the arrays horizontally
stacked_array = np.hstack((array1, array2))

# Display the original arrays and the resulting stacked array
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nHorizontally Stacked Array:")
print(stacked_array)


Array 1:
[1 2 3]

Array 2:
[4 5 6]

Horizontally Stacked Array:
[1 2 3 4 5 6]


#### You can also use hstack to concatenate arrays with more than one dimension:

In [43]:
# Create two 2D arrays
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Use hstack to stack the matrices horizontally
stacked_matrix = np.hstack((matrix1, matrix2))

# Display the original matrices and the resulting stacked matrix
print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nHorizontally Stacked Matrix:")
print(stacked_matrix)


Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Horizontally Stacked Matrix:
[[1 2 5 6]
 [3 4 7 8]]
