In [1]:
import numpy as np

In [5]:
first_numpy_array = np.array([1,2,3,4])
print(first_numpy_array)

[1 2 3 4]


In [7]:
# array with zeros
array_with_zeros = np.zeros((3,3))
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# array with ones
array_with_ones = np.ones((3,3))
print(array_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [51]:
#create an array full of sevens
x = np.full((4,4),7)
x

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [55]:
#create an 4x4 ndarray with diagonal as 3,4,5,6
x = np.diag([3,4,5,6])
print(x)
#to create alternate diagonal
flip = np.fliplr(x)
flip

[[3 0 0 0]
 [0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]]


array([[0, 0, 0, 3],
       [0, 0, 4, 0],
       [0, 5, 0, 0],
       [6, 0, 0, 0]])

In [61]:
normal_array = np.arange(12).reshape(3,4)
print(normal_array)
print("Taking transpose ")
transpose = normal_array.T
print(transpose)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Taking transpose 
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [68]:
y = np.ones((4,4))
np.fill_diagonal(y, [3,4,5,6])
print(y)
print("Before filling diagonal")
z = np.array([[42,32,12],[43,55,13],[67,23,34]])
print(z)
print("After filling diagonal")
np.fill_diagonal(z,[2,5,7,9])
print(z)

[[3. 1. 1. 1.]
 [1. 4. 1. 1.]
 [1. 1. 5. 1.]
 [1. 1. 1. 6.]]
Before filling diagonal
[[42 32 12]
 [43 55 13]
 [67 23 34]]
After filling diagonal
[[ 2 32 12]
 [43  5 13]
 [67 23  7]]


In [69]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
# array with empty
array_with_empty = np.empty((3,4)) # this fills the array with random values
print(array_with_empty)

[[9.60627475e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 3.73775630e-061 4.71284392e-062 2.57905625e-057]
 [8.24778546e-071 8.69222013e-043 1.87868246e+160 7.99786923e+169]]


In [19]:
# array with arange method
np_arange = np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
#reshape method to change / create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
#linspace for linearly (equal) spaced data elements
np_linspace = np.linspace(1,6,5)
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [23]:
#One dimenional array
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
#two dimentional array
twoD_array = oneD_array.reshape(5,3)
print(twoD_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [27]:
#three dimentional array
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [30]:
my_array = np.arange(12).reshape(2,2,3)
my_array

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Numpy array shapes and axes

In [31]:
np.array(24) #zero dimension array

array(24)

In [32]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [35]:
np.array([[1,12,2],[4,6,7]])

array([[ 1, 12,  2],
       [ 4,  6,  7]])

In [39]:
np.array([[[1,1,1,1],[2,2,2,2],[3,3,3,3]], [[3,3,3,3],[4,4,4,4],[5,5,5,5]]])

array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5]]])

In [45]:
numpy_arr = np.array([[[1,1,1,1],[2,2,2,2],[3,3,3,3]], [[3,3,3,3],[4,4,4,4],[5,5,5,5]]])
numpy_arr.shape

(2, 3, 4)

In [46]:
numpy_arr.ndim

3

In [47]:
numpy_arr.dtype

dtype('int32')

In [48]:
numpy_arr.size

24

In [50]:
print(type(numpy_arr))

<class 'numpy.ndarray'>
